### ISSUE TITLE
upgrade react-router to version 4.x

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js-widget#247]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

This has low priority. As long as version 3.x can fit our needs, we don't have to upgrade it.

**Comment by u9520107** [comment]
Don't start spending too much time on this now. We will be discussing this issue pretty soon and might try to incorporate react-router deeper into the framework. We'll invite you to join our meeting when we settle on a time frame.

**Comment by LingForCC** [comment]
@u9520107  Looks like it is difficult to do the upgrade. Should we close the ticket for now?

**Comment by u9520107** [comment]
@tylerlong After some investigation, the primary feature that we want from react-router-4 is to nest routing in components. But nesting Routes in react-redux's connected components will cause the Route to not respond to routing actions properly. If withRouter was used in conjunction with connect, the app would over render, probably because withRouter wraps the connected component in a higher order component that force re-render the component too much. For now I haven't found a good way to deal with this problem. If we don't utilize this feature, then there is no reason to upgrade to v4.
