### ISSUE TITLE
Need Your Support

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-js-widget#30]
I installed the widget with no problems

but now when I try to login it show authorize page I agree on authorization but  after that I return to login page without any changes

Also you can check my screen shots

* screen 1 [https://s7.postimg.org/5vduhukuj/screen1.png](url)
* screen 2 [https://s8.postimg.org/kp9vdd3id/screen2.png](url)

Thanks

**Comment by changbenny** [comment]
The problem is that the redirected page have to post a message to widgets with auth code after successfully login. You can add following code into your redirected page:
```javascript
window.opener && window.opener.postMessage({
      type: 'oauth',
      value: document.URL
    }, '*')
```
Here is a demo of [working redirected page](https://ringcentral.github.io/ringcentral-js-widget/page/redirect.html), take a look of its source code.

**Comment by changbenny** [comment]
If you can login, please note that your app need proper type and permission(`VoIP Calling` and `Browser-based` app) to make a phone call. Because widgets use [webphone](https://github.com/ringcentral/ringcentral-web-phone) to make phone call.
